### ISSUE TITLE
Reprovision not working

### ISSUE THREAD

**Issue by qanhta2710** [BrandonPlank/rootlessJB4#31]
After i had signed my apple id this popup showed
![9EE67CE3-1101-4439-A94E-3A764EE8588D](https://user-images.githubusercontent.com/26887540/87672186-c14b8900-c79c-11ea-8eb0-cb50b23d3ff5.png)

**Comment by KJThaDon** [comment]
Having same error

**Comment by manpreet-ghost** [comment]
i think this is the problem for two factor authentication because the app ain’t have any optio for otp or something to fill acutually they use a app verification password from over apple id privacy to resign or sign apps nd if they can’t login so mean they can’t have the code to sign that the problem
